### ISSUE TITLE
Compatibility with pytest-sugar

### ISSUE THREAD

**Issue by thedrow** [gowtham-sai/pytest-pspec#3]
[pytest-sugar](https://github.com/Frozenball/pytest-sugar) is a plugin that changes the reporter and makes it nicer.
Since this plugin also implements a reporter, we need to provide an integration point for those who use both.

**Comment by gwthm-in** [comment]
@thedrow I didn't understand the point of using 2 reporters. Can you explain what is your use case and why you need to use 2 different reporters?

**Comment by thedrow** [comment]
This reporter is nice because it changes the description of the test.
The other one is nice because it changes the UX of pytest to be nicer.
It'd be nice to combine them.
