### ISSUE TITLE
boring UserWarning

### ISSUE THREAD

**Issue by mpyatishev** [gowtham-sai/pytest-pspec#4]
Hello!

I get a warning every time I use pytest-pspec:
```
python3.7/site-packages/pytest_pspec/plugin.py:77:
UserWarning: Argument(s) ('config',)
which are declared in the hookspec can not be found in this hook call
res = self.config.hook.pytest_report_teststatus(report=report)
```

```
$ pytest --version
This is pytest version 4.4.0
setuptools registered plugins:
  pytest-pspec-0.0.3
  pytest-mock-1.10.3
  pytest-asyncio-0.10.0
```

What can be done about it?

**Comment by pmneve** [comment]
Getting annoyed by these warnings.  Can this pr be merged and deployed asap?

**Comment by montanaflynn** [comment]
If anyone else hits this issue I recommend just using the fork:

`pip3 install 'https://github.com/ROpdebee/pytest-pspec/archive/master.zip'`

**Comment by peteretep** [comment]
Any chance this can be merged?
